#+STARTUP: hidestars odd
#+STARTUP: showeverything
#+TODO: TODO IN-PROGRESS WAITING DONE

* TODO Use https://code.google.com/p/nodefinder/ for node auto-discovery.

* TODO gen_server means a single thread. how do i turn this into multi-threaded server?
  the problem is that since the timer thread runs the stabilization
  method periodically, gen_server is tied up with handling that
  message. If another request comes in, it times out and that kills
  the gen_server. There's gotta be a better way.

* IN-PROGRESS implement a storage layer
** IN-PROGRESS migrate keys (what to do with keys stored on a node that failed? memcached-like non-durability?)
** IN-PROGRESS implement memcached protocol

* DONE learn how to reload code on a gen_server.
  CLOSED: [2015-03-03 Tue 23:31]


* DONE the network system detects nodes that are disconnected.
  CLOSED: [2015-04-08 Wed 23:23] using monitors instead.
  see if there's any way to hook into that for joining/leaving a cluster of nodes.
  error message:
  =ERROR REPORT==== 4-Mar-2015::08:28:45 ===
  + Node n1@anooparyal not responding ++
  + Removing (timedout) connection ++

    had to replace asterisk with a plus.

To run a node do this:
erl -sname n1@localhost -boot start_sasl -sasl sasl_error_logger '{file, "log.n1.log"}'

then, run
% net_adm:ping(n1@localhost).
net_amd:world().
chord:start().
chord:status().
chord:join().
chord:status().

# or any ID instead of 1.
chord:successor(1).
